background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2

    outer_color = rgb(151515)
    inner_color = rgb(200200200)
    font_color = rgb(10,10,10)

    fade_on_empty = false
    rounding = 10

    position = 0, -20
    halign = center
    valign = center
}
