source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/monitor.conf
source = ~/.config/hypr/configs/variables.conf

source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/decoration.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/misc.conf
source = ~/.config/hypr/configs/input.conf

source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/media.conf
source = ~/.config/hypr/configs/rules.conf

source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/blur.conf
source = ~/.config/hypr/configs/screenshots.conf
