env = WLR_DRM_DEVICES,/dev/dri/card0
env = MOZ_ENABLE_WAYLAND,1
env = OZONE_PLATFORM,wayland

env = GTK_THEME,Adwaita:dark
env = GTK_APPLICATION_PREFER_DARK_THEME,1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24