# =========================================================
# OSD / MEDIA
# =========================================================


# ---------------------------------------------------------
# OUTPUT VOLUME
# ---------------------------------------------------------

bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindel = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

# ---------------------------------------------------------
# MICROPHONE
# ---------------------------------------------------------

bindel = ,XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle

# ---------------------------------------------------------
# BRIGHTNESS
# ---------------------------------------------------------

bindel = ,XF86MonBrightnessUp, exec, swayosd-client --brightness raise
bindel = ,XF86MonBrightnessDown, exec, swayosd-client --brightness lower

# ---------------------------------------------------------
# MEDIA CONTROLS
# ---------------------------------------------------------

bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioPause, exec, playerctl pause
bindl = ,XF86AudioNext, exec, playerctl next
bindl = ,XF86AudioPrev, exec, playerctl previous


# ---------------------------------------------------------
# NIGHT LIGHT
# ---------------------------------------------------------

bind = SUPER SHIFT, N, exec, ~/.config/hypr/scripts/nightlight.sh up

bind = SUPER SHIFT, M, exec, ~/.config/hypr/scripts/nightlight.sh down
