monitor=eDP-1,1920x1080@144,0x0,1

# Default laptop-only setup
monitor = eDP-1, 1920x1080@144, 0x0, 1

# External monitor attached
monitorv2 {
    output = HDMI-A-1
    mode = 1366x768@60
    position = 277x-768
    scale = 1
}

# Reposition laptop when HDMI exists
monitorv2 {
    output = eDP-1
    mode = 1920x1080@144
    position = 0x0
    scale = 1
}


# Laptop monitor workspaces
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1

# External monitor workspaces
workspace = 4, monitor:HDMI-A-1, default:true
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1