# Exec Once
exec-once = waybar
exec-once = awww-daemon
exec-once = awww img /home/priyazsh/Pictures/Wallpapers/Build.png
exec-once = swaync
exec-once = swayosd-server
exec-once = hyprsunset
# exec-once = bash -c "sleep 1 && swayosd-server"
